@startuml
actor user

node "Azure (jose_hoyos)"{
    node "Container Instance"{
        [apiTest.py]
    }       
}

node "Azure (jose.hoyos)"{

    package "Blob Storage"{
        storage filetest{
            file avro
            file csv
        }
    }

    database DBTest #00BEF2 {
        map Departments{
            Id => int
            Department => string
        }
        map Employees{
            Id => int
            Name => string
            DateHired => datetime
            Department_Id => int
            Job_Id => int
        }
        map Jobs{
            Id => int
            Job => string
        }
        
    }
}


user -> [apiTest.py]: http Request
[apiTest.py] --> DBTest: overwrite
[apiTest.py] --> filetest: read/write file
Departments .> Employees
Jobs ..> Employees
@enduml
