@startuml
actor user

node "Azure"{

    database DBTest #00BEF2 {
        card Departments
        card Employees
        card Jobs
    }

    package "Blob Storage"{
        map filetest{
            avro => csv
        }
    }

    node "Container Instance"{
        [apiTest.py]
    }
}


user -> [apiTest.py]: http Request
[apiTest.py] -> Departments: overwrite
[apiTest.py] -> Employees: overwrite 
[apiTest.py] -> Jobs: overwrite 
[apiTest.py] --> filetest: read/write file
Departments .> Employees
Jobs ..> Employees
@enduml
